### ISSUE TITLE
DoublyLinkedList implementation can be safer.

### ISSUE THREAD

**Issue by mental32** [blasrodri/tangled-doubly-list#1]
Currently the struct impl looks like this:

```rust
pub struct DoublyLinkedList<T> {
    head: *mut Node<T>,
    tail: *mut Node<T>,
}
```

notice that in [tokio](https://github.com/tokio-rs/tokio/blob/master/tokio/src/util/linked_list.rs#L16) and [alloc](https://github.com/rust-lang/rust/blob/master/library/alloc/src/collections/linked_list.rs#L38) the inner node fields aren't raw mutable pointers but instead `Option<NonNull<Node<T>>`.

I suggest having them as such @blasrodri :)

**Comment by blasrodri** [comment]
Thanks @mental32 
This is a doubly linked list. Can I still use the same _structure_ even though there are pointers from two elements to the same node at the same time?

**Comment by mental32** [comment]
I'm not sure what you mean, could you elaborate a little? @blasrodri

**Comment by blasrodri** [comment]
@mental32 
https://doc.rust-lang.org/beta/std/ptr/struct.NonNull.html
> This is often the correct thing to use when building data structures using raw pointers, but is ultimately more dangerous to use because of its additional properties. If you're not sure if you should use NonNull<T>, just use *mut T!

**Comment by blasrodri** [comment]
@mental32 check https://github.com/blasrodri/tangled-doubly-list/pull/4
